# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Olg4NE8NYm9f2wSlU3W7wzxHNRc2DjG
"""

resposta = input("deseja continuar no sistema? (sim/nao): ").lower()

if resposta == "sim":
  print("continuando...")
else:
  print("encerrando...")

uf = input("digite a sigla do seu estado (ex: sp, rj): ").upper()

print("f"estado cadastrado: (uf))